"use client";

import { Download, FileText, Printer, Type } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import type { SearchResult, GroupedSearchResult } from "@/lib/search";
import { formatTimestamp } from "@/lib/timestamp";

interface DownloadReportButtonProps {
  query: string;
  viewMode: "flat" | "grouped";
  flatResults?: SearchResult[];
  groupedResults?: GroupedSearchResult;
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

function sanitizeFilename(query: string): string {
  return query.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 50);
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function generateMarkdown(
  query: string,
  flatResults?: SearchResult[],
  groupedResults?: GroupedSearchResult,
): string {
  const lines: string[] = [];
  lines.push("# Podlog Search Report");
  lines.push("");
  lines.push(`**Search term:** "${query}"`);

  if (groupedResults) {
    lines.push(
      `**Found in** ${groupedResults.totalEpisodes} episode${groupedResults.totalEpisodes !== 1 ? "s" : ""} ` +
      `across ${groupedResults.totalFeeds} podcast${groupedResults.totalFeeds !== 1 ? "s" : ""} ` +
      `(${groupedResults.totalMentions} mention${groupedResults.totalMentions !== 1 ? "s" : ""})`
    );
  } else if (flatResults) {
    lines.push(`**Total results:** ${flatResults.length}`);
  }

  lines.push(`**Exported:** ${new Date().toLocaleDateString()}`);
  lines.push("");

  if (flatResults && flatResults.length > 0) {
    const byEpisode = new Map<string, SearchResult[]>();
    for (const r of flatResults) {
      if (!byEpisode.has(r.episodeId)) byEpisode.set(r.episodeId, []);
      byEpisode.get(r.episodeId)!.push(r);
    }

    for (const results of Array.from(byEpisode.values())) {
      const first = results[0];
      lines.push(`## ${first.episodeTitle ?? "Unknown Episode"}`);
      lines.push(`*${first.feedTitle ?? "Unknown Podcast"}*`);
      lines.push("");
      for (const r of results) {
        const speaker = r.speakerDisplay ?? r.speakerLabel ?? "";
        const speakerPrefix = speaker ? `**${speaker}** ` : "";
        lines.push(`> \`${formatTimestamp(r.startTime)}\` ${speakerPrefix}${stripHtml(r.snippet)}`);
        lines.push("");
      }
      lines.push("---");
      lines.push("");
    }
  } else if (groupedResults) {
    for (const feed of groupedResults.feeds) {
      for (const ep of feed.episodes) {
        lines.push(`## ${ep.episodeTitle}`);
        lines.push(`*${feed.feedTitle}* — ${ep.mentionCount} mention${ep.mentionCount !== 1 ? "s" : ""}`);
        lines.push("");
      }
    }
  }

  lines.push("---");
  lines.push("*Generated by Podlog*");
  return lines.join("\n");
}

function generatePlainText(
  query: string,
  flatResults?: SearchResult[],
  groupedResults?: GroupedSearchResult,
): string {
  const lines: string[] = [];
  lines.push("PODLOG SEARCH REPORT");
  lines.push("====================");
  lines.push("");
  lines.push(`Search term: "${query}"`);

  if (groupedResults) {
    lines.push(
      `Found in ${groupedResults.totalEpisodes} episodes ` +
      `across ${groupedResults.totalFeeds} podcasts ` +
      `(${groupedResults.totalMentions} mentions)`
    );
  } else if (flatResults) {
    lines.push(`Total results: ${flatResults.length}`);
  }

  lines.push(`Exported: ${new Date().toLocaleDateString()}`);
  lines.push("");

  if (flatResults && flatResults.length > 0) {
    const byEpisode = new Map<string, SearchResult[]>();
    for (const r of flatResults) {
      if (!byEpisode.has(r.episodeId)) byEpisode.set(r.episodeId, []);
      byEpisode.get(r.episodeId)!.push(r);
    }

    for (const results of Array.from(byEpisode.values())) {
      const first = results[0];
      lines.push("────────────────────────────────────────");
      lines.push(`${first.episodeTitle ?? "Unknown Episode"}`);
      lines.push(`${first.feedTitle ?? "Unknown Podcast"}`);
      lines.push("");
      for (const r of results) {
        const speaker = r.speakerDisplay ?? r.speakerLabel ?? "";
        const speakerPrefix = speaker ? `${speaker}: ` : "";
        lines.push(`  [${formatTimestamp(r.startTime)}] ${speakerPrefix}${stripHtml(r.snippet)}`);
      }
      lines.push("");
    }
  } else if (groupedResults) {
    for (const feed of groupedResults.feeds) {
      lines.push("────────────────────────────────────────");
      lines.push(feed.feedTitle);
      lines.push("");
      for (const ep of feed.episodes) {
        lines.push(`  ${ep.episodeTitle} — ${ep.mentionCount} mentions`);
      }
      lines.push("");
    }
  }

  lines.push("Generated by Podlog");
  return lines.join("\n");
}

function openPrintView(query: string) {
  window.open(`/search/print?q=${encodeURIComponent(query)}`, "_blank");
}

export default function DownloadReportButton({
  query,
  viewMode,
  flatResults,
  groupedResults,
}: DownloadReportButtonProps) {
  const hasResults =
    (flatResults && flatResults.length > 0) ||
    (groupedResults && groupedResults.feeds.length > 0);

  if (!hasResults) return null;

  function handleExport(format: "markdown" | "text" | "print") {
    const safeQuery = sanitizeFilename(query);
    const flat = viewMode === "flat" ? flatResults : undefined;
    const grouped = viewMode === "grouped" ? groupedResults : undefined;

    switch (format) {
      case "markdown": {
        const content = generateMarkdown(query, flat, grouped);
        downloadFile(content, `podlog-search-${safeQuery}.md`, "text/markdown;charset=utf-8");
        break;
      }
      case "text": {
        const content = generatePlainText(query, flat, grouped);
        downloadFile(content, `podlog-search-${safeQuery}.txt`, "text/plain;charset=utf-8");
        break;
      }
      case "print": {
        openPrintView(query);
        break;
      }
    }
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-1.5">
          <Download size={14} />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuItem onClick={() => handleExport("markdown")} className="gap-2">
          <FileText size={14} />
          <div>
            <div className="text-sm">Markdown (.md)</div>
            <div className="text-[11px] text-muted-foreground">Speaker-attributed dialogue</div>
          </div>
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => handleExport("text")} className="gap-2">
          <Type size={14} />
          <div>
            <div className="text-sm">Plain Text (.txt)</div>
            <div className="text-[11px] text-muted-foreground">Simple format, no markup</div>
          </div>
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => handleExport("print")} className="gap-2">
          <Printer size={14} />
          <div>
            <div className="text-sm">Print / PDF</div>
            <div className="text-[11px] text-muted-foreground">Styled view for browser print</div>
          </div>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
