"use client";

import { useState } from "react";
import { Download, FileText, Printer, Type, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import type { SearchResult, GroupedSearchResult } from "@/lib/search";
import { formatTimestamp } from "@/lib/timestamp";
import { sanitizeFilename } from "@/lib/filename";

interface DownloadReportButtonProps {
  query: string;
  viewMode: "flat" | "grouped";
  flatResults?: SearchResult[];
  groupedResults?: GroupedSearchResult;
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Fetch all flat search results for export (up to 500).
 * This ensures MD/TXT exports always include full segment content
 * regardless of which view mode the user is in.
 */
async function fetchAllResults(query: string): Promise<SearchResult[]> {
  const params = new URLSearchParams({
    q: query,
    page: "1",
    pageSize: "500",
  });
  const resp = await fetch(`/api/search?${params}`);
  if (!resp.ok) throw new Error("Failed to fetch results for export");
  const data = await resp.json();
  return data.results;
}

function generateMarkdown(query: string, results: SearchResult[]): string {
  const lines: string[] = [];
  lines.push("# Podlog Search Report");
  lines.push("");
  lines.push(`**Search term:** "${query}"`);
  lines.push(`**Total results:** ${results.length}`);
  lines.push(`**Exported:** ${new Date().toLocaleDateString()}`);
  lines.push("");

  const byEpisode = new Map<string, SearchResult[]>();
  for (const r of results) {
    if (!byEpisode.has(r.episodeId)) byEpisode.set(r.episodeId, []);
    byEpisode.get(r.episodeId)!.push(r);
  }

  for (const episodeResults of Array.from(byEpisode.values())) {
    const first = episodeResults[0];
    lines.push(`## ${first.episodeTitle ?? "Unknown Episode"}`);
    lines.push(`*${first.feedTitle ?? "Unknown Podcast"}* — ${episodeResults.length} mention${episodeResults.length !== 1 ? "s" : ""}`);
    if (first.episodeUrl) lines.push(`Episode: ${first.episodeUrl}`);
    if (first.audioUrl) lines.push(`RSS audio: ${first.audioUrl}`);
    lines.push("");
    for (const r of episodeResults) {
      const speaker = r.speakerDisplay ?? r.speakerLabel ?? "";
      const speakerPrefix = speaker ? `**${speaker}** ` : "";
      lines.push(`> \`${formatTimestamp(r.startTime)}\` ${speakerPrefix}${stripHtml(r.snippet)}`);
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  lines.push("*Generated by Podlog*");
  return lines.join("\n");
}

function generatePlainText(query: string, results: SearchResult[]): string {
  const lines: string[] = [];
  lines.push("PODLOG SEARCH REPORT");
  lines.push("====================");
  lines.push("");
  lines.push(`Search term: "${query}"`);
  lines.push(`Total results: ${results.length}`);
  lines.push(`Exported: ${new Date().toLocaleDateString()}`);
  lines.push("");

  const byEpisode = new Map<string, SearchResult[]>();
  for (const r of results) {
    if (!byEpisode.has(r.episodeId)) byEpisode.set(r.episodeId, []);
    byEpisode.get(r.episodeId)!.push(r);
  }

  for (const episodeResults of Array.from(byEpisode.values())) {
    const first = episodeResults[0];
    lines.push("────────────────────────────────────────");
    lines.push(`${first.episodeTitle ?? "Unknown Episode"}`);
    lines.push(`${first.feedTitle ?? "Unknown Podcast"} — ${episodeResults.length} mention${episodeResults.length !== 1 ? "s" : ""}`);
    if (first.episodeUrl) lines.push(`Episode: ${first.episodeUrl}`);
    if (first.audioUrl) lines.push(`RSS audio: ${first.audioUrl}`);
    lines.push("");
    for (const r of episodeResults) {
      const speaker = r.speakerDisplay ?? r.speakerLabel ?? "";
      const speakerPrefix = speaker ? `${speaker}: ` : "";
      lines.push(`  [${formatTimestamp(r.startTime)}] ${speakerPrefix}${stripHtml(r.snippet)}`);
    }
    lines.push("");
  }

  lines.push("Generated by Podlog");
  return lines.join("\n");
}

function openPrintView(query: string) {
  window.open(`/search/print?q=${encodeURIComponent(query)}`, "_blank");
}

export default function DownloadReportButton({
  query,
  viewMode,
  flatResults,
  groupedResults,
}: DownloadReportButtonProps) {
  const [loading, setLoading] = useState(false);

  const hasResults =
    (flatResults && flatResults.length > 0) ||
    (groupedResults && groupedResults.feeds.length > 0);

  if (!hasResults) return null;

  async function handleExport(format: "markdown" | "text" | "print") {
    if (format === "print") {
      openPrintView(query);
      return;
    }

    const safeQuery = sanitizeFilename(query, { maxLength: 50, fallback: "query" });

    // Always fetch complete flat results for file exports
    // so both MD and TXT include full segment content
    setLoading(true);
    try {
      const results = await fetchAllResults(query);

      if (format === "markdown") {
        const content = generateMarkdown(query, results);
        downloadFile(content, `podlog-search-${safeQuery}.md`, "text/markdown;charset=utf-8");
      } else {
        const content = generatePlainText(query, results);
        downloadFile(content, `podlog-search-${safeQuery}.txt`, "text/plain;charset=utf-8");
      }
    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setLoading(false);
    }
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-1.5" disabled={loading}>
          {loading ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuItem onClick={() => handleExport("markdown")} className="gap-2">
          <FileText size={14} />
          <div>
            <div className="text-sm">Markdown (.md)</div>
            <div className="text-[11px] text-muted-foreground">Speaker-attributed dialogue</div>
          </div>
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => handleExport("text")} className="gap-2">
          <Type size={14} />
          <div>
            <div className="text-sm">Plain Text (.txt)</div>
            <div className="text-[11px] text-muted-foreground">Simple format, no markup</div>
          </div>
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => handleExport("print")} className="gap-2">
          <Printer size={14} />
          <div>
            <div className="text-sm">Print / PDF</div>
            <div className="text-[11px] text-muted-foreground">Styled view for browser print</div>
          </div>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
