"use client";

import { useState, useRef, useCallback, useEffect, useMemo } from "react";
import { BrainCircuit, Download, FileText, Send, Type, X, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useAudioPlayer } from "@/components/AudioPlayerContext";
import { renderAnswerWithCitations, type Source, type OnCitationClick } from "@/lib/citations";
import { formatTimestamp } from "@/lib/timestamp";

type StreamStatus = "idle" | "connecting" | "streaming" | "done" | "error";

interface Message {
  role: "user" | "assistant";
  content: string;
  sources?: Source[];
}

interface EpisodeChatProps {
  episodeId: string;
  episodeTitle: string;
  feedTitle?: string | null;
  episodeDescription?: string | null;
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim();
}

function sanitizeFilename(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 50) || "episode";
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

interface ConversationMeta {
  feedTitle?: string | null;
  episodeTitle: string;
  episodeDescription?: string | null;
}

function pairMessages(messages: Message[]): { question: string; answer: string; sources: Source[] }[] {
  const pairs: { question: string; answer: string; sources: Source[] }[] = [];
  for (let i = 0; i < messages.length; i++) {
    const m = messages[i];
    if (m.role !== "user") continue;
    const next = messages[i + 1];
    if (next && next.role === "assistant" && next.content) {
      pairs.push({ question: m.content, answer: next.content, sources: next.sources ?? [] });
    }
  }
  return pairs;
}

function generateConversationMarkdown(meta: ConversationMeta, messages: Message[]): string {
  const lines: string[] = [];
  lines.push(`# ${meta.feedTitle ?? "Podcast"}`);
  lines.push("");
  lines.push(`## ${meta.episodeTitle}`);
  lines.push("");
  if (meta.episodeDescription) {
    lines.push(stripHtml(meta.episodeDescription));
    lines.push("");
  }
  lines.push(`*Exported: ${new Date().toLocaleString()}*`);
  lines.push("");
  lines.push("---");
  lines.push("");

  const pairs = pairMessages(messages);
  pairs.forEach((pair, idx) => {
    lines.push(`### Q${idx + 1}: ${pair.question}`);
    lines.push("");
    lines.push(pair.answer);
    lines.push("");
    if (pair.sources.length > 0) {
      lines.push(`**Sources (${pair.sources.length}):**`);
      lines.push("");
      for (const s of pair.sources) {
        const speaker = s.speaker_label ? ` **${s.speaker_label}**` : "";
        lines.push(`- \`${s.timestamp ?? formatTimestamp(s.start_time)}\`${speaker} — ${s.text}`);
      }
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  });

  lines.push("*Generated by Podlog*");
  return lines.join("\n");
}

function generateConversationText(meta: ConversationMeta, messages: Message[]): string {
  const lines: string[] = [];
  lines.push(meta.feedTitle ?? "Podcast");
  lines.push("=".repeat((meta.feedTitle ?? "Podcast").length));
  lines.push("");
  lines.push(meta.episodeTitle);
  lines.push("-".repeat(meta.episodeTitle.length));
  lines.push("");
  if (meta.episodeDescription) {
    lines.push(stripHtml(meta.episodeDescription));
    lines.push("");
  }
  lines.push(`Exported: ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push("========================================");
  lines.push("");

  const pairs = pairMessages(messages);
  pairs.forEach((pair, idx) => {
    lines.push(`Q${idx + 1}: ${pair.question}`);
    lines.push("");
    lines.push(`A${idx + 1}: ${pair.answer}`);
    lines.push("");
    if (pair.sources.length > 0) {
      lines.push(`Sources (${pair.sources.length}):`);
      for (const s of pair.sources) {
        const speaker = s.speaker_label ? ` ${s.speaker_label}:` : "";
        lines.push(`  [${s.timestamp ?? formatTimestamp(s.start_time)}]${speaker} ${s.text}`);
      }
      lines.push("");
    }
    lines.push("----------------------------------------");
    lines.push("");
  });

  lines.push("Generated by Podlog");
  return lines.join("\n");
}

export default function EpisodeChat({ episodeId, episodeTitle, feedTitle, episodeDescription }: EpisodeChatProps) {
  const { state: playerState } = useAudioPlayer();
  const playerVisible = !!playerState.src;
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [status, setStatus] = useState<StreamStatus>("idle");
  const [errorMsg, setErrorMsg] = useState("");
  const bottomRef = useRef<HTMLDivElement>(null);
  const abortRef = useRef<AbortController | null>(null);

  // Auto-scroll on new content
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, status]);

  // Abort in-flight request on unmount
  useEffect(() => {
    return () => {
      abortRef.current?.abort();
    };
  }, []);

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      const q = input.trim();
      if (!q) return;

      setInput("");
      setErrorMsg("");
      setStatus("connecting");

      // Append user message and empty assistant placeholder
      setMessages((prev) => [
        ...prev,
        { role: "user", content: q },
        { role: "assistant", content: "" },
      ]);

      abortRef.current?.abort();
      const controller = new AbortController();
      abortRef.current = controller;

      try {
        const resp = await fetch("/api/pipeline/ask", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ question: q, episode_id: episodeId }),
          signal: controller.signal,
        });

        if (!resp.ok || !resp.body) {
          setStatus("error");
          setErrorMsg("Failed to connect to the pipeline API.");
          return;
        }

        const reader = resp.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = lines.pop() || "";

          let currentEvent = "";
          for (const line of lines) {
            if (line.startsWith("event: ")) {
              currentEvent = line.slice(7);
            } else if (line.startsWith("data: ") && currentEvent) {
              const raw = line.slice(6);
              try {
                const data = JSON.parse(raw);
                if (currentEvent === "sources") {
                  setMessages((prev) => {
                    const next = [...prev];
                    next[next.length - 1] = { ...next[next.length - 1], sources: data };
                    return next;
                  });
                  setStatus("streaming");
                } else if (currentEvent === "token") {
                  setStatus("streaming");
                  setMessages((prev) => {
                    const next = [...prev];
                    const last = next[next.length - 1];
                    next[next.length - 1] = { ...last, content: last.content + data.content };
                    return next;
                  });
                } else if (currentEvent === "error") {
                  setErrorMsg(data.message || "Unknown error");
                  setStatus("error");
                } else if (currentEvent === "done") {
                  setStatus((s) => (s === "error" ? "error" : "idle"));
                }
              } catch {
                // skip malformed JSON
              }
              currentEvent = "";
            }
          }
        }

        setStatus((s) => (s === "streaming" ? "idle" : s));
      } catch (err: unknown) {
        if (err instanceof DOMException && err.name === "AbortError") return;
        setStatus("error");
        setErrorMsg("Connection failed. Is the pipeline running?");
      }
    },
    [input, episodeId]
  );

  const isStreaming = status === "connecting" || status === "streaming";
  const hasCompletedExchange = messages.some((m) => m.role === "assistant" && m.content.length > 0);

  const handleExport = useCallback(
    (format: "markdown" | "text") => {
      const meta: ConversationMeta = { feedTitle, episodeTitle, episodeDescription };
      const safe = sanitizeFilename(episodeTitle);
      if (format === "markdown") {
        const content = generateConversationMarkdown(meta, messages);
        downloadFile(content, `podlog-ask-${safe}.md`, "text/markdown;charset=utf-8");
      } else {
        const content = generateConversationText(meta, messages);
        downloadFile(content, `podlog-ask-${safe}.txt`, "text/plain;charset=utf-8");
      }
    },
    [feedTitle, episodeTitle, episodeDescription, messages]
  );

  // Floating trigger button
  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        className={`fixed right-6 z-[60] flex items-center gap-2 rounded-full bg-action px-4 py-3 text-action-foreground shadow-lg hover:bg-action/90 transition-all ${
          playerVisible ? "bottom-40" : "bottom-6"
        }`}
        aria-label="Ask about this episode"
      >
        <BrainCircuit size={18} />
        <span className="text-sm font-medium">Ask</span>
      </button>
    );
  }

  // Chat panel
  return (
    <div className={`fixed right-6 z-[60] flex flex-col w-[calc(100vw-2rem)] sm:w-96 h-[min(28rem,calc(100vh-4rem))] rounded-xl border bg-background shadow-2xl ${
      playerVisible ? "bottom-40" : "bottom-6"
    }`}>
      {/* Header */}
      <div className="flex items-center justify-between gap-2 px-4 py-3 border-b shrink-0">
        <div className="flex items-center gap-2 min-w-0">
          <BrainCircuit size={16} className="text-link shrink-0" />
          <span className="text-sm font-medium truncate">{episodeTitle}</span>
        </div>
        <div className="flex items-center gap-1 shrink-0">
          {hasCompletedExchange && (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <button
                  className="text-muted-foreground hover:text-foreground transition-colors p-1"
                  aria-label="Download conversation"
                  disabled={isStreaming}
                >
                  <Download size={16} />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-48">
                <DropdownMenuItem onClick={() => handleExport("markdown")} className="gap-2">
                  <FileText size={14} />
                  <span className="text-sm">Markdown (.md)</span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => handleExport("text")} className="gap-2">
                  <Type size={14} />
                  <span className="text-sm">Plain Text (.txt)</span>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          )}
          <button
            onClick={() => setIsOpen(false)}
            className="text-muted-foreground hover:text-foreground transition-colors p-1"
            aria-label="Minimize chat"
          >
            <X size={16} />
          </button>
        </div>
      </div>

      {/* Messages area */}
      <div className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
        {messages.length === 0 && (
          <p className="text-sm text-muted-foreground text-center mt-8">
            Ask a question about this episode.
          </p>
        )}

        {messages.map((msg, i) => (
          <MessageBubble key={i} message={msg} episodeId={episodeId} isStreaming={isStreaming && i === messages.length - 1} />
        ))}

        {status === "error" && errorMsg && (
          <div className="text-xs text-destructive bg-destructive/10 rounded-md px-3 py-2">
            {errorMsg}
          </div>
        )}

        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <form onSubmit={handleSubmit} className="flex gap-2 px-4 py-3 border-t shrink-0">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask about this episode..."
          className="flex-1 px-3 py-2 text-sm border border-input rounded-md bg-background text-foreground placeholder:text-muted-foreground focus:outline-hidden focus:ring-1 focus:ring-ring"
          disabled={isStreaming}
          autoFocus
        />
        <Button type="submit" size="sm" disabled={!input.trim() || isStreaming} className="px-3">
          {isStreaming ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
        </Button>
      </form>
    </div>
  );
}

function scrollToTime(secs: number) {
  window.dispatchEvent(
    new CustomEvent("podlog:scroll-to-time", { detail: { secs } }),
  );
}

function handleCitationClick(_episodeId: string, seconds: number) {
  scrollToTime(seconds);
}

function MessageBubble({ message, episodeId, isStreaming }: { message: Message; episodeId: string; isStreaming: boolean }) {
  const rendered = useMemo(
    () =>
      message.role === "assistant" && message.content
        ? renderAnswerWithCitations(message.content, message.sources ?? [], handleCitationClick)
        : null,
    [message.content, message.sources, message.role]
  );

  if (message.role === "user") {
    return (
      <div className="flex justify-end">
        <div className="bg-primary text-primary-foreground rounded-lg px-3 py-2 text-sm max-w-[85%]">
          {message.content}
        </div>
      </div>
    );
  }

  return (
    <div className="flex justify-start">
      <div className="bg-muted rounded-lg px-3 py-2 text-sm max-w-[85%] space-y-2">
        {message.content ? (
          <div className="whitespace-pre-wrap">{rendered}</div>
        ) : isStreaming ? (
          <div className="flex items-center gap-1.5 text-muted-foreground">
            <Loader2 size={12} className="animate-spin" />
            <span className="text-xs">Thinking...</span>
          </div>
        ) : null}

        {message.sources && message.sources.length > 0 && (
          <div className="border-t border-border pt-1.5 mt-1.5">
            <p className="text-xs text-muted-foreground mb-1">
              {message.sources.length} source{message.sources.length !== 1 ? "s" : ""}
            </p>
            <div className="space-y-0.5">
              {message.sources.slice(0, 3).map((s) => (
                <button
                  key={s.chunk_id}
                  type="button"
                  onClick={() => scrollToTime(Math.floor(s.start_time))}
                  className="block w-full text-left text-xs text-link hover:underline truncate"
                >
                  {s.timestamp} {s.speaker_label ? `(${s.speaker_label})` : ""} — {s.text.slice(0, 80)}...
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
