/**
 * Tests for apps/web/src/components/EpisodeChatExports.ts (#763).
 * Covers stripHtml, pairMessages, downloadFile, and the two
 * conversation generators (Markdown + plain text).
 */
jest.mock("@/lib/dateFormat", () => ({
  formatDateTime: () => "2026-05-30 12:00",
}));
jest.mock("@/lib/timestamp", () => ({
  formatTimestamp: (secs: number) => `T${secs}`,
}));

import {
  stripHtml,
  downloadFile,
  pairMessages,
  generateConversationMarkdown,
  generateConversationText,
} from "@/components/EpisodeChatExports";
import type { Message } from "@/components/EpisodeChatMessage";
import type { Source } from "@/lib/citations";

function src(partial: Partial<Source>): Source {
  return {
    chunk_id: 1,
    episode_id: "e1",
    episode_title: "Ep 1",
    speaker_label: null,
    start_time: 0,
    end_time: 1,
    timestamp: "0:00",
    text: "hello",
    similarity: 0.9,
    ...partial,
  };
}

describe("stripHtml", () => {
  it("strips tags and collapses whitespace", () => {
    expect(stripHtml("<p>hello   <b>world</b></p>")).toBe("hello world");
  });

  it("handles empty input", () => {
    expect(stripHtml("")).toBe("");
  });

  it("collapses newlines and tabs to single spaces", () => {
    expect(stripHtml("a\n\nb\tc")).toBe("a b c");
  });
});

describe("pairMessages", () => {
  it("pairs consecutive user → assistant messages", () => {
    const msgs: Message[] = [
      { role: "user", content: "Q1" },
      { role: "assistant", content: "A1", sources: [src({ chunk_id: 1 })] },
      { role: "user", content: "Q2" },
      { role: "assistant", content: "A2" },
    ];
    const pairs = pairMessages(msgs);
    expect(pairs).toHaveLength(2);
    expect(pairs[0]).toMatchObject({ question: "Q1", answer: "A1" });
    expect(pairs[0].sources).toHaveLength(1);
    expect(pairs[1]).toMatchObject({ question: "Q2", answer: "A2", sources: [] });
  });

  it("skips unmatched user messages (no following assistant)", () => {
    const msgs: Message[] = [
      { role: "user", content: "Q1" },
      { role: "user", content: "Q2" },
    ];
    expect(pairMessages(msgs)).toEqual([]);
  });

  it("skips when assistant has empty content", () => {
    const msgs: Message[] = [
      { role: "user", content: "Q1" },
      { role: "assistant", content: "" },
    ];
    expect(pairMessages(msgs)).toEqual([]);
  });

  it("returns [] for an empty list", () => {
    expect(pairMessages([])).toEqual([]);
  });
});

describe("downloadFile", () => {
  const origCreateURL = URL.createObjectURL;
  const origRevoke = URL.revokeObjectURL;

  beforeEach(() => {
    URL.createObjectURL = jest.fn(() => "blob:fake");
    URL.revokeObjectURL = jest.fn();
  });
  afterEach(() => {
    URL.createObjectURL = origCreateURL;
    URL.revokeObjectURL = origRevoke;
  });

  it("creates a Blob, triggers a click on an anchor, then cleans up", () => {
    const clickSpy = jest.fn();
    const origCreateElement = document.createElement.bind(document);
    const createSpy = jest
      .spyOn(document, "createElement")
      .mockImplementation((tag: string) => {
        const el = origCreateElement(tag);
        if (tag === "a") (el as HTMLAnchorElement).click = clickSpy;
        return el;
      });

    downloadFile("hello", "file.txt", "text/plain");

    expect(URL.createObjectURL).toHaveBeenCalledTimes(1);
    const blobArg = (URL.createObjectURL as jest.Mock).mock.calls[0][0];
    expect(blobArg).toBeInstanceOf(Blob);
    expect(blobArg.type).toBe("text/plain");
    expect(clickSpy).toHaveBeenCalledTimes(1);
    expect(URL.revokeObjectURL).toHaveBeenCalledWith("blob:fake");

    createSpy.mockRestore();
  });
});

describe("generateConversationMarkdown", () => {
  it("includes feed title, episode title, stripped description, and export timestamp", () => {
    const md = generateConversationMarkdown(
      {
        feedTitle: "Daily Show",
        episodeTitle: "Episode 5",
        episodeDescription: "<p>About <b>climate</b></p>",
      },
      [],
    );
    expect(md).toContain("# Daily Show");
    expect(md).toContain("## Episode 5");
    expect(md).toContain("About climate");
    expect(md).toContain("*Exported: 2026-05-30 12:00*");
    expect(md).toContain("*Generated by Podlog*");
  });

  it("falls back to 'Podcast' when feedTitle is missing", () => {
    const md = generateConversationMarkdown({ episodeTitle: "E" }, []);
    expect(md).toContain("# Podcast");
  });

  it("omits the description block when description is empty", () => {
    const md = generateConversationMarkdown(
      { episodeTitle: "E", episodeDescription: null },
      [],
    );
    expect(md).not.toContain("About");
  });

  it("renders Q/A pairs with sources, using s.timestamp when present", () => {
    const msgs: Message[] = [
      { role: "user", content: "What happened?" },
      {
        role: "assistant",
        content: "It rained.",
        sources: [
          src({
            timestamp: "1:23",
            speaker_label: "Host",
            text: "It poured.",
          }),
          src({ chunk_id: 2, timestamp: "2:00", text: "All day." }),
        ],
      },
    ];
    const md = generateConversationMarkdown({ episodeTitle: "E" }, msgs);
    expect(md).toContain("### Q1: What happened?");
    expect(md).toContain("It rained.");
    expect(md).toContain("**Sources (2):**");
    expect(md).toContain("`1:23` **Host** — It poured.");
    expect(md).toContain("`2:00` — All day.");
  });

  it("uses formatTimestamp when source has no precomputed timestamp", () => {
    const msgs: Message[] = [
      { role: "user", content: "Q" },
      {
        role: "assistant",
        content: "A",
        sources: [
          src({ timestamp: undefined as unknown as string, start_time: 42, text: "x" }),
        ],
      },
    ];
    const md = generateConversationMarkdown({ episodeTitle: "E" }, msgs);
    expect(md).toContain("`T42`");
  });
});

describe("generateConversationText", () => {
  it("renders headings with = / - underlines and the export timestamp", () => {
    const txt = generateConversationText(
      {
        feedTitle: "Show",
        episodeTitle: "Ep",
        episodeDescription: "<i>blurb</i>",
      },
      [],
    );
    expect(txt).toContain("Show\n====");
    expect(txt).toContain("Ep\n--");
    expect(txt).toContain("blurb");
    expect(txt).toContain("Exported: 2026-05-30 12:00");
    expect(txt).toContain("Generated by Podlog");
  });

  it("falls back to 'Podcast' when feedTitle is missing", () => {
    const txt = generateConversationText({ episodeTitle: "E" }, []);
    expect(txt).toContain("Podcast\n=======");
  });

  it("renders Q/A pairs with sources and uses s.timestamp when set", () => {
    const msgs: Message[] = [
      { role: "user", content: "Q1" },
      {
        role: "assistant",
        content: "A1",
        sources: [
          src({ timestamp: "0:30", speaker_label: "Host", text: "first" }),
          src({ chunk_id: 2, timestamp: "1:00", text: "second" }),
        ],
      },
    ];
    const txt = generateConversationText({ episodeTitle: "E" }, msgs);
    expect(txt).toContain("Q1: Q1");
    expect(txt).toContain("A1: A1");
    expect(txt).toContain("Sources (2):");
    expect(txt).toContain("[0:30] Host: first");
    expect(txt).toContain("[1:00] second");
  });

  it("uses formatTimestamp when source timestamp is empty", () => {
    const msgs: Message[] = [
      { role: "user", content: "Q" },
      {
        role: "assistant",
        content: "A",
        sources: [
          src({ timestamp: undefined as unknown as string, start_time: 99, text: "x" }),
        ],
      },
    ];
    const txt = generateConversationText({ episodeTitle: "E" }, msgs);
    expect(txt).toContain("[T99]");
  });
});
